# Generated by Django 4.0.6 on 2022-07-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('pdate', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('-pdate',),
            },
        ),
    ]
